server:
  port: 8080

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/test_mybatis_generator
        username: root
        password: chengyi123
        driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*.xml     #mapper\u6587\u4EF6\u8DEF\u5F84
  type-aliases-package: com.moerlong.yj.model   #\u5B9E\u4F53\u7C7B\u7684\u5305\u8DEF\u5F84

#pagehelper\u5206\u9875\u63D2\u4EF6
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
